### PR TITLE
Version 1.4.0

### PR DESCRIPTION
**Pull request by verdie-g**

### CODE REVIEW

**Comment by ParthShirolawala** [comment]
Can we have the release as soon as possible please ?I am facing a lot of a problem because of issue #46. Is there any workaround I can do If release is not anytime soon ? If you guys can suggest something.

@ychuzevi @verdie-g

**Review by ychuzevi — APPROVED** [review]

**Comment by ParthShirolawala** [comment]
@ychuzevi Nuget package for version 1.4 is available to use? or latest change will be reflected in present version 1.3 only ?

**Comment by ychuzevi** [comment]
Good question. It should have been published automatically thanks to our appveyor plugin. Not sure why the 1.4.0 nuget is not yet available.

**Comment by ParthShirolawala** [comment]
@ychuzevi 
Is there a way to manually publish the new version for nuget?

**Comment by ychuzevi** [comment]
Hello @ParthShirolawala 
Yes, the nuget is now available.

**Pull request merged**
