### PR TITLE
Feature consumer group events

### PR DESCRIPTION
**Pull request by divan-9**
Fixing shameful untested misbehavior :)
Events were not actually work at all anywhere except ConsumerRouter. I added some tests to be sure

### CODE REVIEW

**Comment by sdanzan** [comment]
Test "RaisesPartitionsRevokedEvent" is failing.

**Comment by divan-9** [comment]
That's TestConsumer_ConsumerGroupHeartbeatErrors . Maybe 20ms of sleeping wasn't enough...

**Comment by sdanzan** [comment]
Mmm, the test consistently fails now, it's not just flaky. Something is broken.

**Comment by sdanzan** [comment]
Or travis has problems, because it just passed :)

**Pull request merged**
