### PR TITLE
Faster Activator

### PR DESCRIPTION
**Pull request by mkjeff**
a trick of hack from https://blogs.msdn.microsoft.com/seteplia/2017/02/01/dissecting-the-new-constraint-in-c-a-perfect-example-of-a-leaky-abstraction/

### CODE REVIEW

**Comment by sdanzan** [comment]
What is the point? You're removing a whole test file, and you're adding some class you don't use (and there's a typo in your filename)...

**Comment by mkjeff** [comment]
I removed it because the file(KafkaConsumerTests.cs) doesn't exist.

**Comment by mkjeff** [comment]
The class added has used for replacing built-in generic type construction when generic type with parameterless constructor constraint.

It can silently replace because the type full name is identical, System.Activator. Or explicitly use in

```c#
T FactoryMethod<T>() where T: new(){
   return new T();
}
```

**Comment by sdanzan** [comment]
Oh, OK, but does this Activator overload actually brings any value here? Did you run some benchmarks?

**Comment by mkjeff** [comment]
my benchmark result: https://github.com/mkjeff/Benchmark/tree/master/FastActivator

**Comment by sdanzan** [comment]
But is it really interesting in this case? Seems to me most of the time will be spent in the deserialization following a constructor call. Can you really see any performance increase in a real Produce or Consume scenario?

**Pull request closed without merging**
